### PR TITLE
Improved Join / Feature Chaining support

### PR DESCRIPTION
**Pull request by ridethepenguin**
Features introduced by this PR:
1. Configurable Feature Chaining setup
2. Support for joins between N-types (thanks to 1.)
3. Support for multiple mappings of the same type
4. Target schema can be included in exported archive

@stempler some doubts you may be able to help me clear up:

1. I have added an `updateTargetSchemaResources` method to `AbstractAppSchemaConfigurator`, which contains duplicated code from `ArchiveProjectWriter`: perhaps you see a way to avoid this duplication?
2. I created and registered as extensions two UI pages, `IncludeSchemaConfigurationPage` and `FeatureChainingConfigurationPage`, which should be selectively displayed, depending on the export format chosen by the user (the first one) and the presence of one or more Join relations in the alignment (the second one); to achieve this, I added some logic to the page classes themselves using PageChangingListeners... I'm not sure if this is the best way to do it though, it feels a bit awkward
3. [This commit](https://github.com/igd-geo/hale/commit/9c8a855c792bb08a0798f09164c1554d8a4eb77c) fixes a couple of unrelated tests which were failing and caused troubles with our build server, and commented a third test class, `OMLReaderTest`, which had failing tests that I couldn't fix: you may want to ignore this commit in the merge, or perhaps you fixed these classes already on master, I didn't check

Thanks for any feedback!

### CODE REVIEW

**Comment by stempler** [comment]
Thanks for the update, @ridethepenguin ! I hope to take a detailed look and try it out soon. Sorry that you did not hear from anyone so far, this is mainly because I have been on holiday and ill.

**Comment by stempler** [comment]
@ridethepenguin on your doubts:

1. What do you see as main problem for removing the duplication? How to create a parameterizable method or where to place the common logic to be accessible from both places? I guess it is not worth to put too much effort into this.
2. At least seems to work well. I think we have been avoiding this kind of problems lacking an idea how to solve this well. You are more than welcome if you see a way to generalize this (and include it in the HaleWizardPage class).
3. The changed schema URL we fixed as well, for other parts I see how this could be a problem.
    - How do you execute the tests? Using `build.sh commitStage`?
    - What is the problem with the OMLReader test? Are all tests in there failing? Could it be an issue with the JRE version?

**Comment by ridethepenguin** [comment]
@stempler 
1. I am unsure where the common logic should be best placed: a static method in a helper class would do, but where should I put it (i.e. which class, which module)? But if you think it's not worth the effort, I'll leave it as is.
2. Great. If I ever come up with a more general solution, I'll issue a separate PR.
3. I'm running the tests both with `build.sh commitStage` and by running the `Tests.product` in Eclipse. When I do the former, sometimes the test report has `<testsuite failures=">0" ...`, but I see no `testcase` tag with an error message, which makes it really hard to debug.
If I run it from Eclipse, `OMLReaderTest` is failing with this exception:
```
1 failures:
1) eu.esdihumboldt.hale.oml.test.OMLReaderTest
org.apache.ws.commons.schema.XmlSchemaException: Il tipo di elemento "meta" deve terminare con la corrispondente tag finale "</meta>".
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:391)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:425)
	at org.apache.ws.commons.schema.XmlSchemaCollection.read(XmlSchemaCollection.java:451)
	at eu.esdihumboldt.hale.io.xsd.reader.XmlSchemaReader.execute(XmlSchemaReader.java:284)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractIOProvider.execute(AbstractIOProvider.java:102)
	at eu.esdihumboldt.hale.common.core.io.impl.AbstractImportProvider.execute(AbstractImportProvider.java:74)
	at eu.esdihumboldt.hale.oml.test.OMLReaderTest.readXMLSchema(OMLReaderTest.java:998)
	at eu.esdihumboldt.hale.oml.test.OMLReaderTest.loadAlignment(OMLReaderTest.java:965)
	at eu.esdihumboldt.hale.oml.test.OMLReaderTest.load(OMLReaderTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:128)
	at de.fhg.igd.equinox.test.app.runner.TestExecutor.executeTests(TestExecutor.java:91)
	at de.fhg.igd.equinox.test.app.runner.TestRunner.execute(TestRunner.java:86)
	at de.fhg.igd.equinox.test.app.TestRunnerApplication.run(TestRunnerApplication.java:72)
	at de.fhg.igd.equinox.test.app.TestRunnerApplication.run(TestRunnerApplication.java:1)
	at de.fhg.igd.equinox.test.app.internal.AbstractApplication.run(AbstractApplication.java:55)
	at de.fhg.igd.equinox.test.app.internal.AbstractApplication.start(AbstractApplication.java:37)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.equinox.internal.app.AnyThreadAppLauncher.run(AnyThreadAppLauncher.java:26)
	at java.lang.Thread.run(Thread.java:745)
```

The exception message is localized, in english it would read: `element type <meta> must be terminated by the matching end tag </meta>`
Any clue?

**Comment by stempler** [comment]
@ridethepenguin 
1. The ProjectIO helper class would be good place for such a method I think. I will merge your commits as they are now. If you want to refactor this you are welcome to provide that later.
3. No idea. When I run it I don't get any problems - really strange. As the OML stuff is mainly obsolete (you only need it when loading HALE <=2.1 projects) and there will likely not be any change to it, it doesn't really hurt when those tests are not run.

**Pull request merged**
